site_name: Ruchitha Siliveru

theme:
  name: materia

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra:
  social:
    - type: github
      link: https://github.com/ruchitax/resume
    # Add other social links as needed
