site_name: Ruchitha Siliveru

nav:
  - Home: index.md

theme:
  name: material
  markdown_extensions:
    - pymdownx

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<username>
    - icon: fontawesome/solid/envelope
      link: mailto:someone@example.com

  social_links:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/<username>
      name: Follow me on Twitter

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/<username>
      name: Connect on LinkedIn

  footer_social_links:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/<username>
      name: Twitter

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/<username>
      name: LinkedIn